class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats2'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'clone2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.UsageCommand = 'usage2'

BotCommands = _BotCommands()
