class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mega'
        self.UnzipMirrorCommand = 'unzipmega'
        self.TarMirrorCommand = 'tarmega'
        self.CancelMirror = 'cancelmega'
        self.CancelAllCommand = 'cancelallmega'
        self.ListCommand = 'listmega'
        self.StatusCommand = 'statusmega'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restartmega'
        self.StatsCommand = 'statsmega'
        self.HelpCommand = 'helpmega'
        self.LogCommand = 'logmega'
        self.SpeedCommand = 'speedtestmega'
        self.CloneCommand = 'clonemega'
        self.WatchCommand = 'watchmega'
        self.TarWatchCommand = 'tarwatchmega'
        self.DeleteCommand = 'delmega'
        self.UsageCommand = 'usagemega'

BotCommands = _BotCommands()
